from Compression import CompressionSelector
from Authentication import AuthenticationSelector
from Authorization import AuthorizationSelector
from Reset import ResetSelector
from Documentation import DocumentationSelector
from Exceptions import ExceptionSelector
from Continue import ContinueSelector
from Map import MapSelector
